name: Deploy React App

on: 
  push: 
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
  workflow_dispatch:

jobs:
  deployment:
    strategy:
      matrix:
        command: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - name: get rep code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: ${{matrix.command}}
        run: npm run ${{matrix.command}}
