name: Deploy React App

on: 
  push: 
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get rep code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint App
        run: npm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get rep code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build App
        run: npm run build

  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get rep code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Deploy
        run: echo "12345"
