name: Test React App

on: 
  push: 
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get rep code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
